// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Character struct {
	ID     sql.NullInt64 `json:"id"`
	WordID int64         `json:"word_id"`
	Value  string        `json:"value"`
}

type Document struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Word struct {
	ID    sql.NullInt64 `json:"id"`
	DocID int64         `json:"doc_id"`
	Value string        `json:"value"`
}
